# ------------------------------------------------------------------
# 📜 คาถา DevOps อัตโนมัติสำหรับโปรเจกต์ Searth โดย อาจารย์ป๊อด
# ------------------------------------------------------------------
# นี่คือชื่อคาถาของมึง จะแสดงในหน้า Actions
name: Build and Deploy PodSearth to GitHub Pages

# ------------------------------------------------------------------
# ✨ ทริกเกอร์: จะร่ายคาถานี้เมื่อไหร่?
# ------------------------------------------------------------------
on:
  # เมื่อมีการ push โค้ดขึ้นไปที่ branch 'main'
  push:
    branches: ["main"]
  # อนุญาตให้รัน workflow นี้เองได้จากหน้า Actions (เผื่ออยาก deploy เอง)
  workflow_dispatch:

# ------------------------------------------------------------------
# 🔒 กำหนดสิทธิ์: ให้คาถามีพลังในการเขียนข้อมูลลง GitHub Pages
# ------------------------------------------------------------------
permissions:
  contents: read
  pages: write
  id-token: write

# ------------------------------------------------------------------
# ⚙️ ขั้นตอนการทำงานของคาถา (Jobs)
# ------------------------------------------------------------------
jobs:
  # --- ขั้นตอนที่ 1: Build (สร้างและตรวจสอบ) ---
  build:
    # รันบนเครื่องเซิร์ฟเวอร์ Ubuntu ล่าสุด
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout: ดึงโค้ดของมึงจาก repo มาไว้บนเครื่องเซิร์ฟเวอร์
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Pages: เตรียมสภาพแวดล้อมสำหรับ GitHub Pages
      - name: ⚙️ Setup GitHub Pages
        uses: actions/configure-pages@v5

      # 3. Upload Artifact: บรรจุไฟล์เว็บของมึง (HTML, CSS, JS) เตรียมส่งขึ้นสวรรค์
      # ในที่นี้คือทุกไฟล์ในโปรเจกต์ของมึง
      - name: 📦 Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # '.' หมายถึงทุกอย่างในโฟลเดอร์โปรเจกต์

  # --- ขั้นตอนที่ 2: Deploy (ส่งขึ้นสวรรค์!) ---
  deploy:
    # จะทำงานก็ต่อเมื่อขั้นตอน 'build' สำเร็จเท่านั้น
    needs: build
    # ตั้งค่าสภาพแวดล้อมการ deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # รันบนเครื่องเซิร์ฟเวอร์ Ubuntu ล่าสุด
    runs-on: ubuntu-latest
    steps:
      # 1. Deploy: นำไฟล์ที่บรรจุไว้จากขั้นตอน build ไป deploy จริงๆ
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
